using CodeExploder.Domain;
using Xunit;

namespace CodeExploder.Analysis.Tests;

public sealed class RepoMapperTests : IDisposable
{
    private readonly DirectoryInfo _root = Directory.CreateTempSubdirectory("codeexploder-analysis-tests-");

    public void Dispose() => _root.Delete(recursive: true);

    private static GitStats EmptyGit => new(0, 0, new Dictionary<string, int>());

    private void WriteFile(string relativePath, string content)
    {
        var full = Path.Combine(_root.FullName, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllText(full, content);
    }

    private void WriteBytes(string relativePath, byte[] content)
    {
        var full = Path.Combine(_root.FullName, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllBytes(full, content);
    }

    private RepoMap Map(GitStats? git = null, RepoMapper? mapper = null) =>
        (mapper ?? new RepoMapper()).Map(_root.FullName, git ?? EmptyGit);

    private static RepoFile Get(RepoMap map, string path) => map.Files.Single(f => f.Path == path);

    [Fact]
    public void NodeModulesBecomesOneSyntheticVendoredEntry()
    {
        WriteFile("index.js", "x = 1\n");
        WriteFile("node_modules/pkg/index.js", "y = 2\n");
        WriteFile("node_modules/pkg/deep/util.js", "z = 3\n");

        var map = Map();

        var vendored = Assert.Single(map.Files, f => f.Path.StartsWith("node_modules", StringComparison.Ordinal));
        Assert.Equal("node_modules/", vendored.Path);
        Assert.True(vendored.Excluded);
        Assert.Equal("vendored", vendored.ExcludeReason);
        Assert.Equal(0, vendored.SizeBytes);
        Assert.Equal(1, map.AnalyzedFileCount);
    }

    [Fact]
    public void RolesAndDerivedListsAreDetected()
    {
        WriteFile("Program.cs", "class Program { static void Main() { } }\n");
        WriteFile("App.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\" />\n");
        WriteFile("tests/CalcTests.cs", "class CalcTests { }\n");
        WriteFile("README.md", "# Hello\nwords\n");
        WriteFile(".github/workflows/ci.yml", "on: push\n");

        var map = Map();

        Assert.True(Get(map, "Program.cs").Role.HasFlag(FileRole.EntryPoint));
        Assert.True(Get(map, "App.csproj").Role.HasFlag(FileRole.Manifest));
        Assert.True(Get(map, "tests/CalcTests.cs").Role.HasFlag(FileRole.Test));
        Assert.True(Get(map, "README.md").Role.HasFlag(FileRole.Doc));
        Assert.True(Get(map, ".github/workflows/ci.yml").Role.HasFlag(FileRole.Ci));
        Assert.Contains("Program.cs", map.EntryPoints);
        Assert.Contains(".github/workflows/ci.yml", map.CiConfigs);
        Assert.Contains("msbuild", map.BuildSystems);
    }

    [Fact]
    public void NulByteFileIsExcludedAsBinaryContent()
    {
        WriteBytes("weird.cs", [0x63, 0x6C, 0x61, 0x00, 0x73, 0x73]);

        var file = Get(Map(), "weird.cs");

        Assert.True(file.Excluded);
        Assert.Equal("binary-content", file.ExcludeReason);
    }

    [Fact]
    public void LongLinesAndMinFilenameAreExcludedAsMinified()
    {
        WriteFile("bundle.js", new string('x', 400));
        WriteFile("app.min.js", "x\n");

        var map = Map();

        Assert.Equal("minified", Get(map, "bundle.js").ExcludeReason);
        Assert.Equal("minified", Get(map, "app.min.js").ExcludeReason);
    }

    [Fact]
    public void LockfilesBinaryTypesAndUnrecognizedAreExcluded()
    {
        WriteFile("package-lock.json", "{}\n");
        WriteBytes("logo.png", [1, 2, 3]);
        WriteFile("LICENSE", "MIT License\ncopy freely\n");

        var map = Map();

        Assert.Equal("lockfile", Get(map, "package-lock.json").ExcludeReason);
        Assert.Equal("binary-type", Get(map, "logo.png").ExcludeReason);
        var license = Get(map, "LICENSE");
        Assert.Equal("unrecognized", license.ExcludeReason);
        Assert.Equal("", license.Language);
    }

    [Fact]
    public void OversizedFileIsExcludedAsTooLarge()
    {
        WriteFile("huge.cs", new string('a', 1_100_000));

        Assert.Equal("too-large", Get(Map(), "huge.cs").ExcludeReason);
    }

    [Fact]
    public void GeneratedFilesAreExcludedByNameAndByMarker()
    {
        WriteFile("Grid.Designer.cs", "class Grid { }\n");
        WriteFile("Api.cs", "// <auto-generated>\nclass Api { }\n");

        var map = Map();

        Assert.Equal("generated", Get(map, "Grid.Designer.cs").ExcludeReason);
        Assert.Equal("generated", Get(map, "Api.cs").ExcludeReason);
    }

    [Fact]
    public void LanguageStatsAggregateBytesAndPercents()
    {
        // 10 lines x (29 chars + newline) = 300 bytes of C#; 4 x 25 = 100 bytes of Python.
        WriteFile("a.cs", string.Concat(Enumerable.Repeat(new string('a', 29) + "\n", 10)));
        WriteFile("b.py", string.Concat(Enumerable.Repeat(new string('b', 24) + "\n", 4)));

        var map = Map();

        Assert.Equal(400, map.TotalBytes);
        Assert.Equal(2, map.Languages.Count);
        Assert.Equal(new LanguageStat("C#", 1, 300, 75), map.Languages[0]);
        Assert.Equal(new LanguageStat("Python", 1, 100, 25), map.Languages[1]);
    }

    [Fact]
    public void EntryPointOutranksPlainFileOfSimilarSize()
    {
        WriteFile("Program.cs", "class Program { static void Main() { } }\n");
        WriteFile("Helper.cs", "class Helper { static void Help() { } }\n");

        var map = Map();

        Assert.True(Get(map, "Program.cs").Rank > Get(map, "Helper.cs").Rank);
    }

    [Fact]
    public void ChurnFeedsFilesAndTopChurnList()
    {
        WriteFile("a.cs", "class A { }\n");
        WriteFile("b.py", "x = 1\n");
        WriteFile("c.sql", "select 1\n");
        var git = new GitStats(42, 3, new Dictionary<string, int> { ["a.cs"] = 5, ["b.py"] = 2 });

        var map = Map(git);

        Assert.Equal(5, Get(map, "a.cs").Churn);
        Assert.Equal(new[] { new ChurnStat("a.cs", 5), new ChurnStat("b.py", 2) }, map.TopChurnFiles);
        Assert.Equal(42, map.CommitCount);
        Assert.Equal(3, map.ContributorCount);
    }

    [Fact]
    public void FileCapKeepsTopRankedFiles()
    {
        WriteFile("Program.cs", "class Program { static void Main() { } }\n");
        WriteFile("App.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\" />\n");
        WriteFile("a.cs", "class A { }\n");
        WriteFile("b.cs", "class B { }\n");

        var map = Map(mapper: new RepoMapper(maxFiles: 2, maxTextBytes: long.MaxValue));

        Assert.False(Get(map, "Program.cs").Excluded);
        Assert.False(Get(map, "App.csproj").Excluded);
        Assert.Equal("file-cap", Get(map, "a.cs").ExcludeReason);
        Assert.Equal("file-cap", Get(map, "b.cs").ExcludeReason);
        Assert.Equal(0, Get(map, "a.cs").Rank);
        Assert.Equal(2, map.AnalyzedFileCount);
    }

    [Fact]
    public void TextCapExcludesLowestRankedUntilUnderBudget()
    {
        WriteFile("Program.cs", "class Program { static void Main() { } }\n"); // 41 bytes, entry point
        WriteFile("j1.cs", string.Concat(Enumerable.Repeat("// " + new string('a', 36) + "\n", 100))); // 4000 bytes
        WriteFile("j2.cs", string.Concat(Enumerable.Repeat(new string('b', 29) + "\n", 10))); // 300 bytes

        var map = Map(mapper: new RepoMapper(maxFiles: 5_000, maxTextBytes: 4_300));

        Assert.Equal("text-cap", Get(map, "j2.cs").ExcludeReason);
        Assert.False(Get(map, "j1.cs").Excluded);
        Assert.False(Get(map, "Program.cs").Excluded);
        Assert.True(map.TotalBytes <= 4_300);
    }

    [Fact]
    public void ImportFanInRaisesRankOfImportedFile()
    {
        WriteFile("src/util.js", "x = 1\nexports.x = x\n");
        WriteFile("src/lone.js", "x = 1\nexports.x = x\n");
        WriteFile("src/a.js", "import util from './util'\nconsole.log(util)\n");
        WriteFile("src/b.js", "import util from './util'\nconsole.log(util)\n");
        WriteFile("src/c.js", "import util from './util'\nconsole.log(util)\n");

        var map = Map();

        Assert.True(Get(map, "src/util.js").Rank > Get(map, "src/lone.js").Rank);
    }
}
