using System.Text;
using CodeExploder.Domain;

namespace CodeExploder.Analysis;

/// <summary>
/// S1: one filesystem pass over a checkout producing the deterministic repo map
/// (docs/01 §S1). A clone contains only tracked files, so .gitignore is inherently
/// applied; this layers built-in excludes, binary/minified sniffing, generated-file
/// heuristics, role detection, ranking, and the hard file/text caps on top. Excluded
/// files stay in the map with a reason so the tutorial can honestly mention them.
/// </summary>
public sealed class RepoMapper
{
    internal const int DefaultMaxFiles = 5_000;
    internal const long DefaultMaxTextBytes = 25L * 1024 * 1024;

    private const long MaxFileBytes = 1_048_576;
    private const int SniffBytes = 65_536;
    private const int NulSniffBytes = 8_192;
    private const int GeneratedMarkerChars = 4_096;
    private const int MinifiedProbeLines = 200;
    private const int MinifiedAvgLineLength = 300;
    private const int ListCap = 20;
    private const int TopChurnCap = 10;

    private static readonly HashSet<string> ExcludedDirectories = new(StringComparer.OrdinalIgnoreCase)
    {
        "node_modules", "vendor", "dist", "build", "out", "target",
        ".venv", "venv", "__pycache__", "bin", "obj", ".next", ".cache",
    };

    private static readonly HashSet<string> BinaryExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        "png", "jpg", "jpeg", "gif", "ico", "svg",
        "woff", "woff2", "ttf", "otf", "eot",
        "zip", "tar", "gz", "7z", "jar",
        "mp3", "mp4", "wav", "mov", "pdf",
        "dll", "exe", "so", "dylib", "o", "a", "class", "pyc", "wasm", "sqlite",
    };

    private static readonly HashSet<string> LockFiles = new(StringComparer.OrdinalIgnoreCase)
    {
        "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "Cargo.lock",
        "poetry.lock", "packages.lock.json", "composer.lock", "Gemfile.lock", "go.sum",
    };

    private static readonly string[] GeneratedMarkers =
        ["@generated", "<auto-generated", "Code generated by", "DO NOT EDIT"];

    private static readonly string[] GeneratedNameSuffixes =
        [".designer.cs", ".g.cs", ".g.i.cs", "_pb2.py", ".pb.go"];

    private readonly int _maxFiles;
    private readonly long _maxTextBytes;

    public RepoMapper()
        : this(DefaultMaxFiles, DefaultMaxTextBytes)
    {
    }

    internal RepoMapper(int maxFiles, long maxTextBytes)
    {
        _maxFiles = maxFiles;
        _maxTextBytes = maxTextBytes;
    }

    /// <summary>Walks the checkout at <paramref name="workspaceRoot"/> (skipping .git).</summary>
    public RepoMap Map(string workspaceRoot, GitStats git)
    {
        ArgumentNullException.ThrowIfNull(workspaceRoot);
        ArgumentNullException.ThrowIfNull(git);

        var entries = new List<Entry>();
        var packageJsonDirs = new HashSet<string>(StringComparer.Ordinal);
        Walk(new DirectoryInfo(workspaceRoot), "", entries, packageJsonDirs);

        foreach (var entry in entries)
        {
            if (entry.Synthetic)
            {
                continue;
            }

            Classify(entry);
            entry.Role = DetectRole(entry.Path, packageJsonDirs);
            entry.Churn = git.ChurnByPath.GetValueOrDefault(entry.Path);
        }

        var allPaths = entries.Where(e => !e.Excluded).Select(e => e.Path).ToHashSet(StringComparer.Ordinal);
        var importSources = entries
            .Where(e => !e.Excluded && e.Text is not null && e.Language is "JavaScript" or "TypeScript" or "Python")
            .Select(e => (e.Path, e.Language, e.Text!))
            .ToList();
        var fanIn = ImportGraph.ComputeFanIn(importSources, allPaths);

        foreach (var entry in entries)
        {
            entry.Rank = entry.Excluded ? 0 : ComputeRank(entry, fanIn.GetValueOrDefault(entry.Path));
        }

        ApplyCaps(entries);

        entries.Sort((a, b) => string.CompareOrdinal(a.Path, b.Path));
        var analyzed = entries.Where(e => !e.Excluded).ToList();
        var totalBytes = analyzed.Sum(e => e.Size);

        var languages = analyzed
            .GroupBy(e => e.Language, StringComparer.Ordinal)
            .Select(g =>
            {
                var bytes = g.Sum(e => e.Size);
                var percent = totalBytes == 0 ? 0 : Math.Round(bytes * 100.0 / totalBytes, 2);
                return new LanguageStat(g.Key, g.Count(), bytes, percent);
            })
            .OrderByDescending(l => l.Bytes)
            .ThenBy(l => l.Name, StringComparer.Ordinal)
            .ToList();

        var buildSystems = new List<string>();
        foreach (var entry in analyzed)
        {
            if (!entry.Role.HasFlag(FileRole.Manifest))
            {
                continue;
            }

            var fileName = FileNameOf(entry.Path);
            var system = BuildSystemOf(fileName, ExtensionOf(fileName));
            if (system is not null && !buildSystems.Contains(system, StringComparer.Ordinal))
            {
                buildSystems.Add(system);
            }
        }

        var ciConfigs = analyzed.Where(e => e.Role.HasFlag(FileRole.Ci)).Select(e => e.Path).Take(ListCap).ToList();
        var entryPoints = analyzed.Where(e => e.Role.HasFlag(FileRole.EntryPoint)).Select(e => e.Path).Take(ListCap).ToList();

        var topChurn = analyzed
            .Where(e => e.Churn > 0)
            .OrderByDescending(e => e.Churn)
            .ThenBy(e => e.Path, StringComparer.Ordinal)
            .Take(TopChurnCap)
            .Select(e => new ChurnStat(e.Path, e.Churn))
            .ToList();

        var files = entries
            .Select(e => new RepoFile(e.Path, e.Language, e.Size, e.Excluded, e.Reason, e.Role, e.Churn, e.Rank))
            .ToList();

        return new RepoMap(
            files, languages, buildSystems, ciConfigs, entryPoints, topChurn,
            git.CommitCount, git.ContributorCount, totalBytes);
    }

    private static void Walk(DirectoryInfo directory, string prefix, List<Entry> entries, HashSet<string> packageJsonDirs)
    {
        foreach (var info in directory.EnumerateFileSystemInfos())
        {
            var relativePath = prefix.Length == 0 ? info.Name : prefix + "/" + info.Name;
            if (info is DirectoryInfo subdirectory)
            {
                if (string.Equals(info.Name, ".git", StringComparison.Ordinal))
                {
                    continue;
                }

                if (IsExcludedDirectory(info.Name, prefix))
                {
                    // Represent the whole skipped subtree as one synthetic entry so
                    // counts stay honest without walking huge trees.
                    entries.Add(new Entry
                    {
                        Path = relativePath + "/",
                        FullPath = subdirectory.FullName,
                        Synthetic = true,
                        Excluded = true,
                        Reason = "vendored",
                    });
                    continue;
                }

                Walk(subdirectory, relativePath, entries, packageJsonDirs);
            }
            else if (info is FileInfo file)
            {
                if (string.Equals(file.Name, "package.json", StringComparison.Ordinal))
                {
                    packageJsonDirs.Add(prefix);
                }

                entries.Add(new Entry { Path = relativePath, FullPath = file.FullName, Size = file.Length });
            }
        }
    }

    private static bool IsExcludedDirectory(string name, string parentPrefix) =>
        ExcludedDirectories.Contains(name) ||
        (name.Equals("packages", StringComparison.OrdinalIgnoreCase) &&
         (parentPrefix.EndsWith("node_modules", StringComparison.OrdinalIgnoreCase) ||
          parentPrefix.Contains("node_modules/", StringComparison.OrdinalIgnoreCase)));

    private static void Classify(Entry entry)
    {
        var fileName = FileNameOf(entry.Path);
        var ext = ExtensionOf(fileName);
        entry.Language = LanguageMap.FromPath(entry.Path) ?? "";

        string? reason = null;
        if (ext is not null && BinaryExtensions.Contains(ext))
        {
            reason = "binary-type";
        }
        else if (LockFiles.Contains(fileName))
        {
            reason = "lockfile";
        }
        else if (fileName.Contains(".min.", StringComparison.OrdinalIgnoreCase))
        {
            reason = "minified";
        }
        else if (entry.Size > MaxFileBytes)
        {
            reason = "too-large";
        }
        else
        {
            var (hasNul, text) = Sniff(entry.FullPath, entry.Size);
            if (hasNul)
            {
                reason = "binary-content";
            }
            else
            {
                entry.Text = text;
                if (IsGenerated(fileName, text))
                {
                    reason = "generated";
                }
                else if (LooksMinified(text))
                {
                    reason = "minified";
                }
                else if (entry.Language.Length == 0)
                {
                    reason = "unrecognized";
                }
            }
        }

        if (reason is not null)
        {
            entry.Excluded = true;
            entry.Reason = reason;
        }
    }

    private static (bool HasNul, string Text) Sniff(string fullPath, long size)
    {
        var length = (int)Math.Min(size, SniffBytes);
        var buffer = new byte[length];
        int read;
        using (var stream = File.OpenRead(fullPath))
        {
            read = stream.ReadAtLeast(buffer, length, throwOnEndOfStream: false);
        }

        var hasNul = buffer.AsSpan(0, Math.Min(read, NulSniffBytes)).IndexOf((byte)0) >= 0;
        return hasNul ? (true, "") : (false, Encoding.UTF8.GetString(buffer, 0, read));
    }

    private static bool IsGenerated(string fileName, string text)
    {
        foreach (var suffix in GeneratedNameSuffixes)
        {
            if (fileName.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        var probe = text.Length <= GeneratedMarkerChars ? text : text[..GeneratedMarkerChars];
        foreach (var marker in GeneratedMarkers)
        {
            if (probe.Contains(marker, StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static bool LooksMinified(string text)
    {
        if (text.Length == 0)
        {
            return false;
        }

        var lines = 0;
        long chars = 0;
        var i = 0;
        while (i < text.Length && lines < MinifiedProbeLines)
        {
            var newline = text.IndexOf('\n', i);
            var end = newline < 0 ? text.Length : newline;
            chars += end - i;
            lines++;
            if (newline < 0)
            {
                break;
            }

            i = newline + 1;
        }

        return lines > 0 && (double)chars / lines > MinifiedAvgLineLength;
    }

    private static FileRole DetectRole(string path, HashSet<string> packageJsonDirs)
    {
        var segments = path.Split('/');
        var fileName = segments[^1];
        var ext = ExtensionOf(fileName);

        var role = FileRole.None;
        if (IsEntryPoint(fileName, segments, packageJsonDirs))
        {
            role |= FileRole.EntryPoint;
        }

        if (IsTest(fileName, segments))
        {
            role |= FileRole.Test;
        }

        if (IsDoc(ext, segments))
        {
            role |= FileRole.Doc;
        }

        if (IsManifest(fileName, ext))
        {
            role |= FileRole.Manifest;
        }

        if (IsCi(path, fileName))
        {
            role |= FileRole.Ci;
        }

        return role;
    }

    private static bool IsEntryPoint(string fileName, string[] segments, HashSet<string> packageJsonDirs)
    {
        if (fileName is "Program.cs" or "Main.java" or "main.rs" or "main.py" or "app.py"
            or "manage.py" or "__main__.py" or "main.c" or "main.cpp")
        {
            return true;
        }

        if (fileName is "main.go")
        {
            if (segments.Length == 1)
            {
                return true;
            }

            for (var i = 0; i < segments.Length - 1; i++)
            {
                if (string.Equals(segments[i], "cmd", StringComparison.Ordinal))
                {
                    return true;
                }
            }

            return false;
        }

        if (fileName is "index.js" or "index.ts")
        {
            var dir = segments.Length == 1 ? "" : string.Join('/', segments, 0, segments.Length - 1);
            return packageJsonDirs.Contains(dir);
        }

        return false;
    }

    private static bool IsTest(string fileName, string[] segments)
    {
        for (var i = 0; i < segments.Length - 1; i++)
        {
            var segment = segments[i];
            if (segment.Equals("test", StringComparison.OrdinalIgnoreCase) ||
                segment.Equals("tests", StringComparison.OrdinalIgnoreCase) ||
                segment.Equals("__tests__", StringComparison.OrdinalIgnoreCase) ||
                segment.Equals("spec", StringComparison.OrdinalIgnoreCase) ||
                segment.Equals("e2e", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return fileName.EndsWith("Tests.cs", StringComparison.Ordinal)
            || fileName.EndsWith("Test.java", StringComparison.Ordinal)
            || fileName.Contains(".test.", StringComparison.OrdinalIgnoreCase)
            || fileName.Contains(".spec.", StringComparison.OrdinalIgnoreCase)
            || (fileName.StartsWith("test_", StringComparison.Ordinal) && fileName.EndsWith(".py", StringComparison.Ordinal));
    }

    private static bool IsDoc(string? ext, string[] segments)
    {
        if (ext is "md" or "markdown" or "rst" or "txt" or "adoc")
        {
            return true;
        }

        for (var i = 0; i < segments.Length - 1; i++)
        {
            if (segments[i].Equals("docs", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsManifest(string fileName, string? ext) =>
        ext is "csproj" or "sln" or "slnx" or "gemspec"
        || fileName is "package.json" or "go.mod" or "Cargo.toml" or "pyproject.toml" or "pom.xml"
            or "build.gradle" or "build.gradle.kts" or "Makefile" or "CMakeLists.txt"
            or "Gemfile" or "composer.json" or "Directory.Build.props" or "global.json";

    private static bool IsCi(string path, string fileName) =>
        path.StartsWith(".github/workflows/", StringComparison.Ordinal)
        || path.StartsWith(".circleci/", StringComparison.Ordinal)
        || fileName.StartsWith("Dockerfile", StringComparison.Ordinal)
        || fileName is ".gitlab-ci.yml" or "Jenkinsfile" or "azure-pipelines.yml"
        || ((fileName.StartsWith("docker-compose", StringComparison.OrdinalIgnoreCase)
             || fileName.StartsWith("compose.", StringComparison.OrdinalIgnoreCase))
            && (fileName.EndsWith(".yml", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".yaml", StringComparison.OrdinalIgnoreCase)));

    private static string? BuildSystemOf(string fileName, string? ext) => ext switch
    {
        "csproj" or "sln" or "slnx" => "msbuild",
        "gemspec" => "bundler",
        _ => fileName switch
        {
            "package.json" => "npm",
            "go.mod" => "go",
            "Cargo.toml" => "cargo",
            "pyproject.toml" => "pip/pyproject",
            "pom.xml" => "maven",
            "build.gradle" or "build.gradle.kts" => "gradle",
            "Makefile" => "make",
            "CMakeLists.txt" => "cmake",
            "Gemfile" => "bundler",
            "composer.json" => "composer",
            "Directory.Build.props" or "global.json" => "msbuild",
            _ => null,
        },
    };

    private static int ComputeRank(Entry entry, int fanIn)
    {
        var score = 0;
        if (entry.Role.HasFlag(FileRole.EntryPoint))
        {
            score += 1000;
        }

        if (entry.Role.HasFlag(FileRole.Manifest))
        {
            score += 500;
        }

        if (entry.Role.HasFlag(FileRole.Ci))
        {
            score += 200;
        }

        score += entry.Churn * 5;
        score += (int)Math.Log2(entry.Size + 1);
        score += fanIn * 10;

        if (entry.Role.HasFlag(FileRole.Test) || entry.Role.HasFlag(FileRole.Doc))
        {
            score /= 2;
        }

        return score;
    }

    private void ApplyCaps(List<Entry> entries)
    {
        var analyzed = entries.Where(e => !e.Excluded).ToList();
        if (analyzed.Count > _maxFiles)
        {
            var overflow = analyzed
                .OrderByDescending(e => e.Rank)
                .ThenBy(e => e.Path, StringComparer.Ordinal)
                .Skip(_maxFiles);
            foreach (var entry in overflow)
            {
                entry.Excluded = true;
                entry.Reason = "file-cap";
                entry.Rank = 0;
            }

            analyzed = analyzed.Where(e => !e.Excluded).ToList();
        }

        var total = analyzed.Sum(e => e.Size);
        if (total <= _maxTextBytes)
        {
            return;
        }

        var ascending = analyzed
            .OrderBy(e => e.Rank)
            .ThenByDescending(e => e.Size)
            .ThenBy(e => e.Path, StringComparer.Ordinal);
        foreach (var entry in ascending)
        {
            if (total <= _maxTextBytes)
            {
                break;
            }

            entry.Excluded = true;
            entry.Reason = "text-cap";
            entry.Rank = 0;
            total -= entry.Size;
        }
    }

    private static string FileNameOf(string path)
    {
        var slash = path.LastIndexOf('/');
        return slash < 0 ? path : path[(slash + 1)..];
    }

    private static string? ExtensionOf(string fileName)
    {
        var dot = fileName.LastIndexOf('.');
        return dot <= 0 || dot == fileName.Length - 1 ? null : fileName[(dot + 1)..].ToLowerInvariant();
    }

    private sealed class Entry
    {
        public required string Path { get; init; }

        public string FullPath { get; init; } = "";

        public long Size { get; init; }

        public bool Synthetic { get; init; }

        public string Language { get; set; } = "";

        public bool Excluded { get; set; }

        public string? Reason { get; set; }

        public FileRole Role { get; set; }

        public int Churn { get; set; }

        public int Rank { get; set; }

        public string? Text { get; set; }
    }
}
